project_name         = "secure-mini-cloud"
environment          = "dev"
aws_region           = "us-east-2"
app_name             = "incident-tracker"
app_image_tag        = "v3"
app_desired_replicas = 1
app_container_port   = 8080
app_cpu_request      = "100m"
app_cpu_limit        = "500m"
app_memory_request   = "128Mi"
app_memory_limit     = "512Mi"
app_hpa_min_replicas = 1
app_hpa_max_replicas = 4
app_hpa_cpu_target   = 60

prod_namespace                      = "prod"
security_dev_cpu_requests_quota     = "1000m"
security_dev_cpu_limits_quota       = "2000m"
security_dev_memory_requests_quota  = "1Gi"
security_dev_memory_limits_quota    = "2Gi"
security_dev_pod_quota              = "10"
security_prod_cpu_requests_quota    = "2000m"
security_prod_cpu_limits_quota      = "4000m"
security_prod_memory_requests_quota = "2Gi"
security_prod_memory_limits_quota   = "4Gi"
security_prod_pod_quota             = "20"
security_default_cpu_request        = "100m"
security_default_cpu_limit          = "500m"
security_default_memory_request     = "128Mi"
security_default_memory_limit       = "512Mi"
simulate_overprivilege              = false

node_instance_types = ["t3.small", "t3a.small"]
node_capacity_type  = "SPOT"
node_desired_size   = 2
node_min_size       = 2
node_max_size       = 3

enable_observability = true
monitoring_namespace = "monitoring"
prometheus_retention = "7d"
grafana_service_type = "LoadBalancer"
